name: .NET

on:
  push:
    branches:
      - "bug/**"
      - "feature/**"
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Restore NuGet packages
      run: |
        nuget restore
        nuget restore .\testconsole\packages.config -PackagesDirectory .\packages
        nuget restore .\sfidsmultiuserTests\packages.config -PackagesDirectory .\packages

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run Tests
      run: cd sfidsmultiuserTests/bin/Release; dotnet vstest sfidsmultiuserTests.dll
